### ISSUE TITLE
CView::LoadPoolTagText(), crashed as the newline format somehow changed to \n

### ISSUE THREAD

**Issue by EthanZBY** [zodiacon/PoolMonXv2#2]
A little bit strange, both pooltag.txt and the compiled res are \n for newline rather than \r\n.

void CView::LoadPoolTagText() {

		if (strncmp(data, "//", 2) == 0 || _strnicmp(data, "rem", 3) == 0
			|| strncmp(data, "\r\n", 2) == 0 || strncmp(data, "\n", 1) == 0)
			continue;

**|| strncmp(data, "\n", 1) == 0**
has to be added

**Comment by zodiacon** [comment]
I added a fix just in case
